interface WorkSheet {
    period: string;
    niveauHabitation: string;
    typeChantier: string;
    disjoncteur: boolean;
    distanceCompteurPac: number;
    natureMurExt: string;
    naturePlafond: string;
    visiteComble: boolean;
    chantierHabite: boolean;
    grandeEchelle: boolean;
    demandeVoirie: boolean;
    puissanceCompteur: number;
    accesComble: string;
    rueEtroite: boolean;
    typeCouverture: string;
    etatToiture: string;
    typeCharpente: string;
    nbCompartimentComble: number;
    presenceVolige: boolean;
    nbAccesComble: number;
    distanceGpExtUnitInt: number;
    nbTotalRadiateur: number;
    nbRadiateurThermostatique: number;
    typeRadiateur: string;
    positionEauChaude: string;
    hauteurDuSol: number;
    espaceSolRequisUnitInt: boolean;
    hauteurRequiseUnitInt: boolean;
    emplacementSplit1: string;
    emplacementSplit2: string;
    emplacementSplit3: string;
    emplacementSplit4: string;
    emplacementSplit5: string;
    emplacementGrpExt: string;
    emplacementSplitMono: string;
    distanceGpExtSplit1: number;
    distanceGpExtSplit2: number;
    distanceGpExtSplit3: number;
    distanceGpExtSplit4: number;
    distanceGpExtSplit5: number;
    nbPompeRelevage: number;
    infosSup: string;
}

export default WorkSheet;
